---
name: CI
on: push
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: "Install Nix ❄️ " 
        uses: cachix/install-nix-action@v18
      - uses: DeterminateSystems/magic-nix-cache-action@main
        name: "Magic Nix Cache!"
      - run: nix flake check --quiet --extra-experimental-features "nix-command flakes"
        name: Run nix flake checks
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Verify with Maven
        run: mvn --no-transfer-progress --batch-mode --update-snapshots -Dstyle.color=always verify
